### ISSUE TITLE
Créer une landing + recueil d'email

### ISSUE THREAD

**Issue by martinregner** [datagir/tco2#1]
Comme pour BCS, créer une landing pour recueillir les mails pour prévenir du lancement

**Comment by martinregner** [comment]
Contenu	
- Le logo/nom du site/outil
-	Une petite description :
« L’outil d'aide à la décision pour l'achat de flottes de véhicules de transport de marchandises.
Comparez le coût et les émissions des technologies de motorisation en fonction de vos besoins et de vos usages. 
Neutre, gratuit et open-source. »
-	La partie email :
« Disponible bientôt. Soyez informés en saisissant votre adresse ci-dessous » + champ email (avec mention RGPD ?)
-	En bas, les logos des soutiens du projet, cliquable pour accéder aux sites :
o	Soutenu par l’ADEME
o	La Fabrique de la Logistique
o	Datagir
o	(à confirmer) IFPEN
o	(à confirmer) TLF
o	(à confirmer) Club Déméter

**Comment by florianpanchout** [comment]
https://tco2.netlify.app/

On a déjà un ndd ?

Je ne sais pas quel logo mettre dans le header : Ademe ou Fabrique de la logistique ?

**Comment by florianpanchout** [comment]
@laem Est ce que tu peux créer une nouvelle propriété Matomo pour ce projet ?

**Comment by martinregner** [comment]
> On a déjà un ndd ?

Non... ils ont pas encore décidé...

> Je ne sais pas quel logo mettre dans le header : Ademe ou Fabrique de la logistique ?

Je demande à Tristan. Peut-être juste FabLog

**Comment by martinregner** [comment]
Le footer est à mettre à jour, ça parle de BCS là ;)

**Comment by florianpanchout** [comment]
Oups, c'est corrigé

**Comment by martinregner** [comment]
Retour de Tristan : 
-	Retirer les logos RF + ADEME du bandeau 
- Ils n'ont pas de logo à ce stade ; propositions : 
   - on rester sur le nom écrit de manière basique en noir
   - on joue sur les couleurs (ex. qui part en noir et fini en vert...)
   - on garde le texte en noir sauf le o de "flotte" qui est une roue (de camion) verte
   
- Remplacer "TCO2" par "Verdir ma flotte" aux différents endroits

-	Ajouter un saut de ligne entre chaque phrase de la description : 
 
![image](https://user-images.githubusercontent.com/46482115/160662848-0ae130e9-c15f-4552-92a3-f6b9a53597e6.png)


-	Ajouter une adresse de contact [contact@lafabriquedelalogistique.fr](mailto:contact@lafabriquedelalogistique.fr)

**Comment by florianpanchout** [comment]
On est sur de vouloir retirer la Marianne ? C'est un peu une obligation du DSFR
