### ISSUE TITLE
saisie km itinéraire

### ISSUE THREAD

**Issue by martinregner** [datagir/tco2#3]
Lorsque l'on saisit un itinéraire, on ne voit pas si cela a été pris en compte (on voit le graphe en dessous bouger si on fait attention)

Serait-il possible d'actualiser les km ? ou au moins les éfficher en dessous en bleu (avec la répartition Urbain / Extra urbain / Autoroute) ?
![image](https://user-images.githubusercontent.com/46482115/167626968-b2b79a47-49b1-4492-b76b-a9f65ad3726e.png)

**Comment by florianpanchout** [comment]
Nope. L'itinéraire change la typologie de route, et pas le kilométrage annuel

**Comment by martinregner** [comment]
Dac je vois.

Pour que l'itinéraire soit bien interprété comme tel, est-ce que l'on peut ajouter un petit texte genre :

**Répartition par mode**
**Manuelle / Via l'itinéraire**
![image](https://user-images.githubusercontent.com/46482115/167644473-c07bff7f-0c35-4766-8170-266f70f5de38.png)

Quand on navigue entre les deux onglets, on ne sait plus ce qui est pris en compte (et ça efface la personnalisation quand on fait des clics entre les deux).
Possible de reprendre les valeurs de l'itinéraire dans **Manuel**  ?

**Comment by florianpanchout** [comment]
Ça aurait été mieux mais je n'ai pas les valeurs de l'itinéraire :/
