### ISSUE TITLE
Modifs logos header et footer

### ISSUE THREAD

**Issue by martinregner** [datagir/tco2#6]
- retirer les logos RF et ADEME du haut de page et ne mettre que le logo Verdir ma flotte
- ajouter le logo Fabrique de la logistique dans le footer à côté de Datagir

**Comment by florianpanchout** [comment]
Je prend quel logo pour la Fabrique ?

https://www.lafabriquedelalogistique.fr/wp-content/uploads/2019/02/LOGO-FAB_LOG.png 

ou 

https://wiki.resilience-territoire.ademe.fr/wiki/Fichier:Logo-retina.jpg

**Comment by martinregner** [comment]
Dans le footer, le logo FabLog (dernière version) peut p-e pointer vers leur site plutôt que vers Datagir non ?

**Comment by florianpanchout** [comment]
Corrigé !
